name: CI for Static WebApp

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t static-webapp-image ./Static-WebApp

      - name: Run container
        run: docker run -d -p 8080:80 static-webapp-image